[project]
name = "python-motion-planning"
version = "0.28.0"
description = "Motion planning algorithms for Python"
maintainers = [
    {name = "Yang Haodong", email = "913982779@qq.com"},
    {name = "Wu Maojia", email = "2223942063@qq.com"}
]
readme = "README.md"
license = {file = "LICENSE"}
requires-python = ">=3.6"
dependencies = [
    "numpy",
    "scipy",
    "matplotlib",
    "cvxopt",
    "osqp",
    "tqdm",
    "torch",
    "torchvision",
    "tensorboard==2.12.0",
    "mkdocs"
]
repository = {type = "git", url = "https://github.com/ai-winter/python_motion_planning.git"}
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: GNU General Public License v3.0",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
]

[build-system]
requires = ["setuptools>=43.0.0", "wheel"]
build-backend = "setuptools.build_meta"